### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by WalkerKnapp** [WalkerKnapp/devolay#11]
At some point between the NDI v3 and v4 SDKs, builds for the Android platform were added to the SDK distribution under $NDILIB_REDIST_FOLDER/Android. As far as I can tell, this isn't documented, but it should be possible to include these builds and make Devolay compatible with android environments. This will require Gradle multi-platform builds and a rewrite of how devolay-java loads devolay-native artifacts.

**Comment by stuartaw** [comment]
I would second this, support for android (which seems quite solid/official in NDI now) would be a huge plus!
There are a small number of existing NDI supporting android apps, however they are generally expensive and not well featured.

**Comment by aaelephant** [comment]
hi, 
Libs failed to load when integrated into anroid environment. The ide used is android studio

**Comment by aaelephant** [comment]
hi  
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.mtool.ndidemo2/cache/devolay-natives9096383232614741647.so" .dynamic section header was not found

**Comment by WalkerKnapp** [comment]
I will be able to take a closer look at this in the next few days. For anyone seeing this thread and not in the loop, since v2.0.0, Devolay has been published with experimental Android binaries. I'll close this issue when they are confirmed working (right now it seems like they aren't).

**Comment by aaelephant** [comment]
Okay, thank you very much and look forward to it

**Comment by aaelephant** [comment]
Hello, is there any progress on the problem, sorry to disturb you, but I am more anxious to use your library here
![image](https://user-images.githubusercontent.com/8765931/123223714-b5675b80-d503-11eb-8d71-53d32c3140d3.png)

**Comment by WalkerKnapp** [comment]
Sorry for not getting back to you faster. I am having a few issues that seem to only pop up using the Android Studio emulator. I just published my latest code to the integrated_builds branch (https://github.com/WalkerKnapp/devolay/tree/integrated_builds), and it seems to crash from a JNI error on the emulator. However, it works fine on the two physical devices I tested it on.

If you can, it would be great if you could download the `devolay-2.0.1-integrated.jar` jar file from the github action and test it in your workflow. Let me know the details of any crashes, if they pop up. 

Edit: https://github.com/WalkerKnapp/devolay/suites/3089380414/artifacts/70557865

To note, you'll be the first person using `integrated` builds, so please make sure to check the [Licensing Considerations section of the README](https://github.com/WalkerKnapp/devolay/tree/integrated_builds#%EF%B8%8Flicensing-considerations%EF%B8%8F) before you publish anything.

**Comment by WalkerKnapp** [comment]
I can only replicate these issues now on x86_64 Android Emulators. I assume this is either an issue with NDI's binary for that platform, or that it's an emulation issue. Either way, I am almost certain that it isn't an error in Devolay (or at most, it is an error in Devolay's buildscript). 

I am going to go ahead and close this issue with release v2.0.2, since it appears to support all physical devices and non-x86_64 emulators. I opened a separate issue for x86_64 emulators (#19). If anyone experiences more issues with pure Android support, feel free to either comment on this issue or open a new issue.
