### ISSUE TITLE
Error when running  assemble 

### ISSUE THREAD

**Issue by arisprung18** [WalkerKnapp/devolay#15]
This  is the error when running ./gradlew assemble and gradlew :devolay-natives:assembleNatives

fatal error: too many errors emitted, stopping now [-ferror-limit=]
13 warnings and 20 errors generated.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':devolay-natives:compileDebugMacosX86-64Cpp'.
> A build operation failed.
      C++ compiler failed while compiling devolay.cpp.
  See the complete log at: file:///Users/ari.sprung/Dev/NDI/devolay/devolay-natives/build/tmp/compileDebugMacosX86-64Cpp/output.txt
   > C++ compiler failed while compiling devolay.cpp.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':devolay-natives:compileReleaseMacosX86-64Cpp'.
> A build operation failed.
      C++ compiler failed while compiling devolay.cpp.
  See the complete log at: file:///Users/ari.sprung/Dev/NDI/devolay/devolay-natives/build/tmp/compileReleaseMacosX86-64Cpp/output.txt
   > C++ compiler failed while compiling devolay.cpp.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7-20200901040000+0000/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s

**Comment by WalkerKnapp** [comment]
Can you post the file:///Users/ari.sprung/Dev/NDI/devolay/devolay-natives/build/tmp/compileReleaseMacosX86-64Cpp/output.txt file?

**Comment by arisprung18** [comment]
[output.txt](https://github.com/WalkerKnapp/devolay/files/5253717/output.txt)
Here it is . Thx!

**Comment by WalkerKnapp** [comment]
This looks like another issue with Macos being unhappy with the standards that work everywhere else. The "-std=c++11" argument should fix it. I will get that pushed tomorrow morning, but a replacing your devolay-natives/build.gradle.kts with https://github.com/WalkerKnapp/devolay/blob/c9d2e9266d4cf939a5db46a0d41183db99624747/devolay-natives/build.gradle.kts should be a temporary fix
