### ISSUE TITLE
OS error when running

### ISSUE THREAD

**Issue by arisprung** [WalkerKnapp/devolay#16]
Getting error :Caused by: java.lang.IllegalStateException: This build of Devolay is not compiled for your OS. Please use a different build or follow the compilation instructions on https://github.com/WalkerKnapp/devolay.

See OS details in screenshot of debug
<img width="719" alt="Screenshot 2020-09-21 140108" src="https://user-images.githubusercontent.com/1506537/93759638-3f039900-fc13-11ea-8cae-ec3810b90717.png">

**Comment by WalkerKnapp** [comment]
Can you look into the contents of your `devolay-java/build/libs/devolay-1.2.0.jar` file and see if there is a `natives/windows/x86-64/devolay-natives.dll` file? If there isn't, try deleting your `devolay-java/build` and `devolay-natives/build` folders and rebuilding. If that doesn't work, I'll try to see if I can replicate this.

**Comment by WalkerKnapp** [comment]
v2.0.0 and v2.0.1 feature a lot of changes to this section of the natives loading code. Can you still replicate this issue on those versions?

**Comment by WalkerKnapp** [comment]
I'm going to go ahead and close this as stale. If anyone encounters a similar issue on the latest version, feel free to open another issue!
