### ISSUE TITLE
compiling instructions

### ISSUE THREAD

**Issue by maxdee** [WalkerKnapp/devolay#2]
Hello, I am trying to see if this can be used with [Processing](https://processing.org/). I am running linux and your readme says "see Compiling" but there are no file or readme section call Compiling.

I tried `gradle build` and got : 
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/mxd/freeliner_stuff/newtek_ndi/devolay/devolay-natives/build.gradle' line: 17

* What went wrong:
A problem occurred evaluating project ':devolay-natives'.
> Could not get unknown property 'binaries' for object of type org.gradle.language.cpp.internal.DefaultCppLibrary.
```

Any advice?

**Comment by rfikes4** [comment]
I have a Processing example using Haxademic in Eclipse here https://github.com/rfikes4/haxademic-ndi-sender

**Comment by maxdee** [comment]
Thanks for the tip! Unfortunately your binary does not work on my machine.

**Comment by WalkerKnapp** [comment]
@maxdee I've added compiling instructions to the readme. It must have completely slipped my mind to write the instructions down after referring to them. If following them gives the same result, what build toolchain are you using?
I'm sorry about the delay, but thank you for leaving an issue!

**Comment by WalkerKnapp** [comment]
I'm closing this, as the latest version (1.1.1) is bundled with builds for Windows, MacOS, and Linux. Thank you for leaving an issue!
