### ISSUE TITLE
Hello, how to integrate NDI_send_H264

### ISSUE THREAD

**Issue by tianhonglilei** [WalkerKnapp/devolay#26]
Hello, I would like to use the NDIlib_Send_H264 module in the NDI SDK, what do I need to do? I look forward to your reply, thank you!

**Comment by WalkerKnapp** [comment]
Hello! Off the top of my head, I believe that is a function in the advanced SDK, which Devolay doesn't currently support (#25). We do plan on supporting it in the future, though!

In the meantime, your best workaround while staying in pure java will be decoding your h264 data with JavaCpp-ffmpeg. See this project for an example of how to do that https://github.com/WalkerKnapp/video2ndi

**Comment by tianhonglilei** [comment]
@WalkerKnapp Hello! Thanks for your reply and suggestions, I will try to build the latest NDI Advanced SDK.
