### ISSUE TITLE
Java 8 support?

### ISSUE THREAD

**Issue by Skriglitz** [WalkerKnapp/devolay#3]
Hi there. I was actually in the process of writing my own NDI wrapper for Java when I came across yours . However i noticed it appears to be using Java 9+ cleaner class despite being set to Java 8 compatibility in the gradle build file. Will there be any plans to make this work with Java 8 as well?

**Comment by WalkerKnapp** [comment]
Thank you for the bug report 👍 I assumed my IDE would tell me about a discrepancy like that. Release 1.1.0 should now support Java 8, but it is moreso a hotfix, as it now requires resources to be closed with a try-with-resources block or the #close function. In a future release the automatic closing will be implemented using PhantomReferences. Sorry about the delay, and I hope this helps! Let me know if there are any other issues.
