### ISSUE TITLE
Java examples for receiving audio

### ISSUE THREAD

**Issue by moster67** [WalkerKnapp/devolay#7]
Hello and many thanks for your project.
 
I have been using your library to provide the B4J platform with a wrapper. B4J is a "basic-language" and is using JavaFX under the hood. This is a project I am doing with another user, @bdunkleysmith, who started it all for B4J and who has already asked you a few questions.
That said, I am new to the world of NDI and broadcasting and have a lot to learn. Also I am not a Java Expert.

The B4J wrapper is now more or less complete. I will shortly publish it here on GitHub with sources and I will of course credit you and link to your project.

I am now starting to use it in B4J and all your java examples are running nicely. I also managed to get a NDI feed of a YouTube video, using the VLC plugin, and showing the video without hardly any drops of frames in my B4J app. The only thing I cannot get to work is to get the audio from the VLC feed - so far it is only video with no audio - and play it together with the video. I wrote a java wrapper class, AudioPlayer, adapted for B4J which (should) let me play the audio. See this [pastebin](https://pastebin.com/xhwr2tuQ):

In my B4J method, I get the AudioFrame, fill it into a ByteBuffer and then return a ByteArray which I feed my AudioPlayer java class with. However, I always get an "Exit java.lang.IllegalArgumentException" similar to : "No line matching interface SourceDataLine supporting format PCM_SIGNED 44100.0 Hz, 1024 bit, stereo, 256 bytes/frame, little-endian is supported". So I believe I am not passing on a correct formatted ByteArray or arguments to my AudioPlayer class.

This is the code in B4J which should be quite readable also for Java users:
`
Case Rx1.AUDIO
				Log("Audio data received (" & audioframe.getSamples & ", " & audioframe.getChannelStride & ").")
								
				//'just some logging
				Log(audioframe.GetChannels) '2
				Log(audioframe.GetSampleRate) '44100
				Log(audioframe.GetSamples) '1024
				Log(audioframe.GetChannelStride)
				Log((audioframe.GetChannelStride * audioframe.GetChannels)/8)

				
				Dim audiodata As ByteBuffer
				'Wondering how this should be set up?
				'audiodata.Initialize(audioframe.GetSampleRate * audioframe.GetChannels)
				'audiodata.Initialize((audioframe.GetSampleRate * audioframe.GetChannels * 32) / 8)
				'audiodata.Initialize(audioframe.GetSampleRate * audioframe.GetChannels * 4)
				audiodata.Initialize((audioframe.GetChannelStride * audioframe.GetChannels)/8)
				audiodata=audioframe.GetData
				
				Dim byteArray(audiodata.Capacity) As Byte
				byteArray = Devv.getByteArrayFromByteBuffer(audiodata) 'uses ByteBuffer.Remaining. Seems the fastest way.
				
				
				'starting player 
				'NOTE: This will crash the app unless the correct format is found.
				'once found, the player *should" work
				'if you want to work only with video, remove this part
				ap.Initialize(audioframe.GetSampleRate, audioframe.GetSamples, audioframe.GetChannels, True, False)
				ap.Start(byteArray) 'starts the audioplayer in its own thread
								
				audioframe.close
				Dim audioframe As DevolayAudioFrame
				audioframe.Initialize`

This is a screenshot of the codec-information from VLC of the YouTube I am using as a test:
![image](https://user-images.githubusercontent.com/2834535/71370826-660f3a80-25af-11ea-8ead-a5d744398255.png)

So, me and @bdunkleysmith are both stuck on getting the audio along with the video.
Do you have any ideas about what I am doing wrong?

Alternatively, if you could write a java example of how to receive audio, perhaps together with video, that would be amazing. 

I had a look at your other repository where you receive audio with DisCord but don't think that was something I could apply to this.

Once again, many thanks for your Java wrapper and your great work.

Rgds,
Mike

**Comment by WalkerKnapp** [comment]
I'm sorry for the delay in responding, you've caught me in a bit of a bad spot due to the holidays. I'll be able to get back to you with a better answer in a few days (with an example, hopefully), but from what I can see it looks like you may need to manually transform the audio into a format with a supported SourceDataLine? I've never worked with this API, but I'll be able to go through and get more specific help when I get back.

Again, I apologise for the wait and this hastily written message, and hopefully I'll be able to get back to you soon.

**Comment by bdunkleysmith** [comment]
No need to apologise; it's important that you have some holiday time. So enjoy that and @moster67 and myself will look forward to anything you can come up with.

Looking at the NewTek Managed NDI Receive example which includes audio playback, I note they use one of the methods included in Utilities to "Convert from float planar to float interleaved audio". 

Also in NewTek's SDK documentation I see they mention using the "frame synchronizer" object to effectively convert the incoming audio signal to a "requested sample rate, channel count and number of samples".

But as I said to @moster67 in a separate conversation, I am much closer to achieving the objective of my application using NDI than I ever thought I'd be at this time and so I owe you many thanks.

**Comment by moster67** [comment]
Thank you @WalkerKnapp for your reply. As @bdunkleysmith wrote, there is no rush and no obligation of course. Enjoy your holidays and come back to it if you feel for it and when you have free time.

About the API I used, it was based on samples I found. I am not aware of any other way but perhaps there are better solutions to play audio. 

From the SDK examples, we have seen that NDI uses some utility methods to convert audio. Like these ones:

> // Convert To interleaved 16bpp
'                PROCESSINGNDILIB_API
'                void NDIlib_util_audio_to_interleaved_16s_v2(const NDIlib_audio_frame_v2_t* p_src, NDIlib_audio_frame_interleaved_16s_t* p_dst);
'
'                // Convert from interleaved 16bpp
'                PROCESSINGNDILIB_API
'                void NDIlib_util_audio_from_interleaved_16s_v2(const NDIlib_audio_frame_interleaved_16s_t* p_src, NDIlib_audio_frame_v2_t* p_dst);
'
'                // Convert To interleaved 32bpp
'                PROCESSINGNDILIB_API
'                void NDIlib_util_audio_to_interleaved_32s_v2(const NDIlib_audio_frame_v2_t* p_src, NDIlib_audio_frame_interleaved_32s_t* p_dst);
'
'                // Convert from interleaved 32bpp
'                PROCESSINGNDILIB_API
'                void NDIlib_util_audio_from_interleaved_32s_v2(const NDIlib_audio_frame_interleaved_32s_t* p_src, NDIlib_audio_frame_v2_t* p_dst);

 

I tried to poke around and see the original code of those methods but could not find them. If they are to be used in Java, I guess they must be exposed through your wrapper. But my knowledge is to say the least, not the best and there may be much better ways.

Thank you.

**Comment by WalkerKnapp** [comment]
Thanks for the patience, I finally had the chance to go through and implement everything needed for this. As far as I know, you are right about needing to use a frame-synchronizer and a planarity conversion to properly receive audio like this, but I hadn't implemented it before since personally I've been using mostly the send api and hadn't noticed it

I just released `1.2.0`, which implements all the NDIlib_util functions in `DevolayUtilities`, and `NDIlib_framesync` in `DevolayFrameSync`. The examples `FrameSyncExample` and `MonitorExample` use them. I based `MonitorExample` on using AudioSystem to monitor audio, so hopefully, it'll be especially useful here.

Specifically, I think the issue you were having was that you were creating an AudioFormat using a frame's sample count as the bits-per-sample value. 1024 is common for a sample count, but the error message was giving it as the bps. Even then, from debugging `MonitorExample`, I could only get 16s audio to work on Windows, so a conversion would have been needed.

Let me know if you can get your system working, and thank you for the issue!

**Comment by moster67** [comment]
Many thanks for your update! You've been really busy in the last days. Much appreciated.
I will in the coming days go over my B4J-wrapper and adapt it with your latest updates and additions and then test it. 
Either me or @bdunkleysmith will publish our results here but I am pretty sure it will be fine now.

Thanks.
Mike
